version: '3.7'

# sudo docker compose up

services:

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - HOME
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${HOME}/docker_volumes/homeAssistant/data:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
